### ISSUE TITLE
v0.0.7 master branch: local variable 'timeout_task' referenced before assignment

### ISSUE THREAD

**Issue by luop0812** [mila-iqia/milabench#164] opened 2023-07-11 21:03 UTC
I have tried to run Milabench cloned from the v0.0.7 master branch in a Conda environment. The code failed to run for almost all of the benchmarks with the same error message, for example:

$ milabench run --select resnet50
Traceback (most recent call last):
  File "/gpfs/gibbs/project/hpcprog/pl543/milabench2/milabench/multi.py", line 177, in do_run
    await exec_plan.execute("run", timeout=True, timeout_delay=600)
  File "/gpfs/gibbs/project/hpcprog/pl543/milabench2/milabench/executors.py", line 140, in execute
    timeout_task.cancel()
UnboundLocalError: local variable 'timeout_task' referenced before assignment
resnet50 UnboundLocalError: local variable 'timeout_task' referenced before assignment

Please take a look and let me know if you need further information.

**Comment by Delaunay** [comment] 2023-07-12 11:11
Thank you for the issue, 
A PR has been made to fix that particular issue.

Although it seems that this issue, is only partly the cause of the failure as at least one timeout_task should have been created for the benchmark.

`milabench run --select resnet50` should be spawning one benchmark per gpu.
Are you running on a system with NVIDIA GPUs ?

**Comment by luop0812** [comment] 2023-07-17 16:53
Yes, I am running it on a system with NVIDIA GPUs. In particular, I have being using one A100 with 40G device memory.

**Comment by Delaunay** [comment] 2024-02-09 14:30
Closing this, the root cause was addressed, feel free to reopen if the issue persists

**Closed by Delaunay** 2024-02-09 14:30 UTC
