### ISSUE TITLE
scaling benchmark fails

### ISSUE THREAD

**Issue by nileshnegi** [mila-iqia/milabench#1] opened 2020-07-02 08:58 UTC
Scaling benchmark fails even after I have set ```DATAROOT``` and ```OUTDIR``` variables, although other benchmarks work.
Scaling works if we declare an additional environment variable ```MILARUN_DATAROOT``` or if we replace occurences of ```$MILARUN_DATAROOT``` with ```$DATAROOT``` in ```milarun/cli.py``` and ```milarun/lib/experiment.py```

```
root@7a175f4ea7a2:/workspace/milabench# milarun jobs profiles/standard.json -d $DATAROOT -o $OUTDIR --name scaling
+ sync
+ sysctl vm.drop_caches=3
sysctl: setting key "vm.drop_caches": Read-only file system
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.0 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.1 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.2 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.3 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2, 3]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.4 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2, 3, 4]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.5 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2, 3, 4, 5]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.6 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2, 3, 4, 5, 6]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Running: nocache milarun run milarun.models.scaling:main --experiment-name standard.scaling --job-id 0.7 --out /lvol/nilesh/mila-new/data/results-2020-07-02.07:33:43 --dataroot /lvol/nilesh/mila-new/data --extra {"job": {"prepare": ["sync", "sysctl vm.drop_caches=3"], "exec_prefix": ["nocache"], "partition_scheme": {"type": "gpu-progression"}, "experiment": "milarun.models.scaling:main", "arguments": {"--network": "alexnet", "--batch-size": 64, "--cuda": true, "--max-count": 50000}}, "devices": [0, 1, 2, 3, 4, 5, 6, 7]} -- --network alexnet --batch-size 64 --cuda --max-count 50000
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
milarun: error: no dataroot specified,  please use --dataroot/-d or set $MILARUN_DATAROOT
Total time: 35.46s
```

**Comment by Delaunay** [comment] 2023-02-23 16:24
I am going to close this.
The issue is about a bench that was removed in the newer version.

**Closed by Delaunay** 2023-02-23 16:24 UTC
